//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 05. 04. 19:18:01
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Autoker
{
    public partial class Kereskedes {

        public Kereskedes()
        {
            this.Autos = new List<Auto>();
            this.Elados = new List<Elado>();
            OnCreated();
        }

        public short KereskedesId { get; set; }

        public string Nev { get; set; }

        public string Jegyzekszam { get; set; }

        public virtual Cim Cim { get; set; }

        public virtual IList<Auto> Autos { get; set; }

        public virtual IList<Elado> Elados { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
