//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 05. 01. 21:06:49
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Autoker
{
    public partial class Cim {

        public Cim()
        {
            OnCreated();
        }

        public short CimId { get; set; }

        public string Varos { get; set; }

        public string Utca { get; set; }

        public string Hazszam { get; set; }

        public virtual Kereskedes Kereskedes { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
