//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 05. 01. 13:19:28
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Autoker
{
    public partial class Elado {

        public Elado()
        {
            OnCreated();
        }

        public short EladoId { get; set; }

        public string Nev { get; set; }

        public string Telszam { get; set; }

        public string Szuldatum { get; set; }

        public string email { get; set; }

        public string jelszo { get; set; }

        public virtual Kereskedes Kereskedes1 { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
